const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  switchTab:        (tabName) => ipcRenderer.send("switch-tab", tabName),
  onTabActive:      (cb)      => ipcRenderer.on("tab-active", (_e, name) => cb(name)),
  onTabProgress:    (cb)      => ipcRenderer.on("tab-progress", (_e, name, event) => cb(name, event)),
  setTopBarHeight:  (h)       => ipcRenderer.send("set-topbar-height", h),
  reloadActiveTab:  (ignoreCache) => ipcRenderer.send("reload-active-tab", ignoreCache),
  resetTabSession:  (tabName)  => ipcRenderer.invoke("reset-tab-session", tabName),
  setProxy:         (config)  => ipcRenderer.invoke("set-proxy", config),
  clearProxy:       ()        => ipcRenderer.invoke("clear-proxy"),
  pickExtension:    ()        => ipcRenderer.invoke("pick-extension"),
  installExtension: (id)      => ipcRenderer.invoke("install-extension", id),
  listExtensions:   ()        => ipcRenderer.invoke("list-extensions"),
  toggleExtension:  (id, enabled) => ipcRenderer.invoke("toggle-extension", id, enabled),
  uninstallExtension: (id)    => ipcRenderer.invoke("uninstall-extension", id),
  openExternal:     (url)     => ipcRenderer.send("open-external", url),
  listWireguardConfigs: () => ipcRenderer.invoke("wg-list"),
  importWireguardConfigs: () => ipcRenderer.invoke("wg-import"),
  removeWireguardConfig: (id) => ipcRenderer.invoke("wg-remove", id),
  connectWireguard: (id) => ipcRenderer.invoke("wg-connect", id),
  disconnectWireguard: () => ipcRenderer.invoke("wg-disconnect"),
  onWireguardStatus: (cb) => ipcRenderer.on("wg-status", (_event, status) => cb(status)),
  tunnelCancel: () => ipcRenderer.invoke("tunnel-cancel"),
  onTunnelGate: (cb) => ipcRenderer.on("tunnel-gate", (_event, info) => cb(info)),
  setContentTheme:  (theme)   => ipcRenderer.send("set-content-theme", theme),
  openclawStatus: () => ipcRenderer.invoke("openclaw-status"),
  openclawStart: () => ipcRenderer.invoke("openclaw-start"),
  openclawDashboard: () => ipcRenderer.invoke("openclaw-dashboard"),
  onOpenClawDown: (cb) => ipcRenderer.on("openclaw-down", (_event, info) => cb(info)),
  tasksList: () => ipcRenderer.invoke("tasks-list"),
  tasksCreate: (payload) => ipcRenderer.invoke("tasks-create", payload),
  tasksUpdate: (payload) => ipcRenderer.invoke("tasks-update", payload),
  tasksDelete: (id) => ipcRenderer.invoke("tasks-delete", id),
  tasksSetStatus: (payload) => ipcRenderer.invoke("tasks-set-status", payload),
  tasksAddAssignment: (payload) => ipcRenderer.invoke("tasks-add-assignment", payload),
  tasksRemoveAssignment: (payload) => ipcRenderer.invoke("tasks-remove-assignment", payload),
  tasksOpen: (payload) => ipcRenderer.invoke("tasks-open", payload),
  tasksSetWorkspace: (workspace) => ipcRenderer.invoke("tasks-set-workspace", workspace),
  tasksToggleWorkspace: () => ipcRenderer.invoke("tasks-toggle-workspace"),
  tasksClearCapture: () => ipcRenderer.invoke("tasks-clear-capture"),
  onTasks: (cb) => ipcRenderer.on("tasks-status", (_event, status) => cb(status)),
  googleStatus: () => ipcRenderer.invoke("google-status"),
  googleSignIn: () => ipcRenderer.invoke("google-sign-in"),
  googleApplyAll: () => ipcRenderer.invoke("google-apply-all"),
  googleUseShared: (service) => ipcRenderer.invoke("google-use-shared", service),
  googleUseOther: (service) => ipcRenderer.invoke("google-use-other", service),
  onGoogle: (cb) => ipcRenderer.on("google-status", (_event, status) => cb(status)),
});
