export const invokeChannels = [
  "reset-tab-session",
  "set-proxy",
  "clear-proxy",
  "pick-extension",
  "install-extension",
  "list-extensions",
  "toggle-extension",
  "uninstall-extension",
  "wg-list",
  "wg-import",
  "wg-remove",
  "wg-connect",
  "wg-disconnect",
  "tunnel-cancel",
  "openclaw-status",
  "openclaw-start",
  "openclaw-dashboard",
  "tasks-list",
  "tasks-create",
  "tasks-update",
  "tasks-delete",
  "tasks-set-status",
  "tasks-add-assignment",
  "tasks-remove-assignment",
  "tasks-open",
  "tasks-set-workspace",
  "tasks-toggle-workspace",
  "tasks-clear-capture",
  "google-status",
  "google-sign-in",
  "google-apply-all",
  "google-use-shared",
  "google-use-other",
  "services-list",
  "services-set-route",
  "services-set-hidden",
  "services-reorder",
  "services-add-account",
  "services-set-account",
  "services-set-label",
  "services-remove-account",
  "services-add-custom",
  "services-remove-custom",
  "services-set-hotkey",
  "services-set-spellcheck",
  "compare-start",
  "compare-insert",
  "compare-stop",
  "find-in-page",
  "find-stop",
  "update-download",
  "update-install",
] as const;

export const sendChannels = [
  "switch-tab",
  "set-topbar-height",
  "reload-active-tab",
  "open-external",
  "set-content-theme",
] as const;

export type InvokeChannel = (typeof invokeChannels)[number];
export type SendChannel = (typeof sendChannels)[number];
